gesdinet_jwt_refresh_token:
    cookie:
        enabled: true
        same_site: lax
        path: /
        domain: null
        http_only: true
        secure: false
        partitioned: false
        remove_token_from_body: true

    refresh_token_class: App\Entity\RefreshToken
    ttl: 25920000
    ttl_update: true
    return_expiration: true