# config/packages/nelmio_cors.yaml
nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['http://192.168.178.66:3000']
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        expose_headers: ['Set-Cookie']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['http://192.168.178.66:3000']
            allow_credentials: true