framework:
  rate_limiter:
    anonymous_api:
      policy: fixed_window
      limit: 2
      interval: '1 minute'
      cache_pool: cache.app

    authenticated_api:
      policy: sliding_window
      limit: 2
      interval: '1 minute'
      cache_pool: cache.app
