services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Listener\DomainListener\PasswordResetRequestedEventListener:
        tags:
            - { name: kernel.event_listener, event: App\Event\PasswordResetRequestedEvent, method: onPasswordResetRequested }

    App\Listener\DomainListener\UserDeletionListener:
        tags:
            - { name: kernel.event_listener, event: App\Event\UserDeletionRequestEvent, method: onUserDeletionRequested }

    App\Listener\DomainListener\CartCalculationSubscriber:
        tags:
            - { name: 'kernel.event_listener', event: 'cart.calculated', method: 'onCartCalculated' }

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
